### ISSUE TITLE
Some albums are not downlaoading

### ISSUE THREAD

**Issue by saptarshi1701057** [monuyadav016/Saavn-Downloader#15]
Brother some albums are downloading while others are not
below is the attached error

saptarshi@saptarshi:~/Saavn-Downloader$ python3 download_reloaded.py -o /home/saptarshi/Desktop/
Enter the URL : https://www.jiosaavn.com/album/saari-ki-saari/qTWlshnxUCY_
Traceback (most recent call last):
  File "download_reloaded.py", line 82, in <module>
    obj.run()
  File "download_reloaded.py", line 70, in run
    album.start_download()
  File "/home/saptarshi/Saavn-Downloader/scripts/content/album.py", line 64, in start_download
    self.getAlbumID()
  File "/home/saptarshi/Saavn-Downloader/scripts/content/album.py", line 32, in getAlbumID
    self.albumID = soup.select(".play")[0]["onclick"]
IndexError: list index out of range

**Comment by monuyadav016** [comment]
This is an edge case. I modified the code for finding albumID. It should be working fine now. Also thank you for submitting the issue.

**Comment by saptarshi1701057** [comment]
you are welcome brother
